language: java
addons:
  sonarcloud:
    organization: "mesa963-github"
    token:
      secure: Vo7BZmmNK62eP3oLEI/nHAyoYPGWig1JdnW41oOPwQQDQEqPxM2Nb5SLvCObFQ98BiTRoLkWEYBxLgjbQL5LGcwne9MhbiVw6qPz+QW7Mx8QXHDNSnGT0bCdNV0U7L5hMX7c0l2RlplF8o4KOKWmJEIksXMNoWid8swHB/Fi3tAWs5kgZ7oGD3Rba8oCmdWrUnxzkHgby+eRKQT37vhE1hX0pH+emKQl0CxDlbMfO54BJqMaL+80VRu0vqYHCS/YtnDmpMvYW/nFhnDL8FngBcP6U5liEjvAlrojTRtBjesfsnZaltiiE0oxIOI7VB92LeGBGahE2zUUa0KLOm4Tfu7vAl7cLJyPyf6hcK7MW8jfHSs+NJqQntnNzjx0Q4i+AfJZ5uXUjj4/mkHagy7URzO0spJ7dZ+TYtQ+747sQFJF6LqSXUZDnni0Fqrl4SArdStUqeTrWq0mIHdgMHxA9evRosxcVDy4Js1ObBmK/sucOEsmJGjOz6WNuv6e/BO4dq3RrANFXKDLhfrpX7Tq9FBF8bFS47awQ1XUirJfIoLxE8UGATy/Xi3jUeOIdylJCBxFSytK06gcC3+guvLcPzC6IV/VTxd1d5VZiJ6hSRjdK5cAveyIT6ZFiTo8o22pE9bEVxhWQs0VeKFC5dJt/LTiP8EAdjgGbkViDSMGAwY=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar